mono: AssemblyInfo.cs Boolean.cs Integer.cs Main.cs Mapping.cs Node.cs Null.cs ParseStream.cs  Scalar.cs Sequence.cs String.cs Binary.cs Timestamp.cs Float.cs WriteStream.cs ParseException.cs
	mcs AssemblyInfo.cs Boolean.cs Integer.cs Main.cs Mapping.cs Node.cs Null.cs ParseStream.cs  Scalar.cs Sequence.cs String.cs Binary.cs Timestamp.cs Float.cs WriteStream.cs ParseException.cs -checked 
